#spring:
#  profiles:
#    active:
#      prod
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: ${SERVER_PORT}
spring:
  redis:
    host: ${REDIS_CONTAINER}
    port: ${REDIS_CONTAINER_PORT}
  datasource:
    url: ${DB_ENDPOINT}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${USERNAME_PASSWORD}
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: Asia/Seoul
      default_batch_fetch_size: 100
    open-in-view: false
file:
  path: ${FILE_PATH}
secret-key: ${SECRET_KEY}